[package]
name = "split_in_pairs"
version = "0.1.0"
authors = ["Ma1982en"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
